spring:
   profiles: 
      active: 
      - dev
---
spring:
   profiles: dev
   application:  
      name: microservicecloud-config-admin-dev
---
spring:
   profiles: test
   application:  
      name: microservicecloud-config-admin-test

https://github.com/zbwandcy/oneRespository.git